{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 3\n +  where 3 = <bound method Random.choice of <random.Random object at 0x0000023DCD6A23A0>>([1, 2, 3])\n +    where <bound method Random.choice of <random.Random object at 0x0000023DCD6A23A0>> = random.choice", "trace": "@pytest.mark.ui\n    def test_1():\n>       assert 1 == random.choice(random_nambers)\nE       assert 1 == 3\nE        +  where 3 = <bound method Random.choice of <random.Random object at 0x0000023DCD6A23A0>>([1, 2, 3])\nE        +    where <bound method Random.choice of <random.Random object at 0x0000023DCD6A23A0>> = random.choice\n\ntests\\test_index_page.py:10: AssertionError"}, "start": 1665310568795, "stop": 1665310568796, "uuid": "244ac667-e31d-41f1-ad6a-aa2b9a4e002a", "historyId": "5c68e5de91020ee2e1fd5a1f6e3cb424", "testCaseId": "27ea5db8220704c922e6b23d27ffafa5", "fullName": "tests.test_index_page#test_1", "labels": [{"name": "tag", "value": "ui"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_index_page"}, {"name": "host", "value": "MSK-1627"}, {"name": "thread", "value": "22628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_index_page"}]}